import { HistoricalEventOutcome } from '@shared/types';
import { HISTORICAL_EVENT_IDS, VENUE_IDS, daysAgo } from './ids';

/**
 * Historical event outcomes (M2 history references).
 * These are the "completed eligible historical events" used in M2
 * context-snapshot retrieval and the AI agreement metrics in M5.
 *
 * All marked synthetic for the prototype.
 */

export const mockHistoricalEvents: HistoricalEventOutcome[] = [
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H001,
    venueId: VENUE_IDS.V006,  // MBPJ Civic Centre
    eventType: 'fair',
    startDatetime: daysAgo(360),
    endDatetime: daysAgo(360) + 6 * 60 * 60 * 1000,
    attendance: 4500,
    registeredCapacity: 3000,
    environment: 'indoor',
    coverage: 'covered',
    seating: 'mixed',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-fire-cert', 'ctrl-medical-team'],
    resourcesPlanned: { police: 10, security: 16, medicalTeams: 1, ambulances: 1, toilets: 20, wasteBins: 50, fireOfficers: 3 },
    resourcesActuallyUsed: { police: 10, security: 14, medicalTeams: 1, ambulances: 1, toilets: 18, wasteBins: 45, fireOfficers: 3 },
    outcomes: { patientPresentations: 8, hospitalTransfers: 1, ambulanceActivations: 1, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 2, fatalities: 0 },
    incidentIds: ['hist-inc-001', 'hist-inc-002'],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['One medical presentation for heat exhaustion. Adequate medical team response.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H002,
    venueId: VENUE_IDS.V002,  // Bukit Jalil
    eventType: 'sports',
    startDatetime: daysAgo(420),
    endDatetime: daysAgo(420) + 5 * 60 * 60 * 1000,
    attendance: 18000,
    registeredCapacity: 87411,
    environment: 'outdoor',
    coverage: 'uncovered',
    seating: 'standing',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-traffic-plan', 'ctrl-medical-team'],
    resourcesPlanned: { police: 40, security: 60, medicalTeams: 4, ambulances: 3, toilets: 80, wasteBins: 200, fireOfficers: 10 },
    resourcesActuallyUsed: { police: 42, security: 65, medicalTeams: 4, ambulances: 3, toilets: 75, wasteBins: 180, fireOfficers: 10 },
    outcomes: { patientPresentations: 25, hospitalTransfers: 3, ambulanceActivations: 3, crowdIncidents: 1, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 4, fatalities: 0 },
    incidentIds: ['hist-inc-003', 'hist-inc-004'],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Effective crowd control at finish line. One minor crowd surge; PDRM contained in 90 seconds.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H003,
    venueId: VENUE_IDS.V002,
    eventType: 'concert',
    startDatetime: daysAgo(550),
    endDatetime: daysAgo(550) + 5 * 60 * 60 * 1000,
    attendance: 22000,
    registeredCapacity: 87411,
    environment: 'outdoor',
    coverage: 'uncovered',
    seating: 'seated',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-fire-cert', 'ctrl-medical-team', 'ctrl-traffic-plan'],
    resourcesPlanned: { police: 55, security: 80, medicalTeams: 6, ambulances: 4, toilets: 90, wasteBins: 220, fireOfficers: 12 },
    resourcesActuallyUsed: { police: 60, security: 85, medicalTeams: 6, ambulances: 4, toilets: 85, wasteBins: 200, fireOfficers: 12 },
    outcomes: { patientPresentations: 38, hospitalTransfers: 4, ambulanceActivations: 4, crowdIncidents: 2, securityIncidents: 1, weatherInterruptions: 0, nearMisses: 6, fatalities: 0 },
    incidentIds: ['hist-inc-005', 'hist-inc-006', 'hist-inc-007'],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Pyrotechnics compliance confirmed. Two crowd surge incidents near stage.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H004,
    venueId: VENUE_IDS.V005,  // Shah Alam Stadium
    eventType: 'festival',
    startDatetime: daysAgo(640),
    endDatetime: daysAgo(640) + 8 * 60 * 60 * 1000,
    attendance: 9500,
    registeredCapacity: 80000,
    environment: 'outdoor',
    coverage: 'uncovered',
    seating: 'mixed',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-medical-team', 'ctrl-fire-cert'],
    resourcesPlanned: { police: 22, security: 32, medicalTeams: 2, ambulances: 2, toilets: 40, wasteBins: 100, fireOfficers: 5 },
    resourcesActuallyUsed: { police: 22, security: 32, medicalTeams: 2, ambulances: 2, toilets: 38, wasteBins: 95, fireOfficers: 5 },
    outcomes: { patientPresentations: 14, hospitalTransfers: 2, ambulanceActivations: 2, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 1, nearMisses: 3, fatalities: 0 },
    incidentIds: [],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['One brief rain interruption; covered stage area used. No significant incidents.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H005,
    venueId: VENUE_IDS.V004,  // Axiata Arena
    eventType: 'cultural',
    startDatetime: daysAgo(280),
    endDatetime: daysAgo(280) + 4 * 60 * 60 * 1000,
    attendance: 2200,
    registeredCapacity: 16000,
    environment: 'indoor',
    coverage: 'covered',
    seating: 'seated',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-fire-cert', 'ctrl-medical-team'],
    resourcesPlanned: { police: 6, security: 10, medicalTeams: 1, ambulances: 1, toilets: 10, wasteBins: 25, fireOfficers: 2 },
    resourcesActuallyUsed: { police: 6, security: 9, medicalTeams: 1, ambulances: 1, toilets: 9, wasteBins: 22, fireOfficers: 2 },
    outcomes: { patientPresentations: 3, hospitalTransfers: 0, ambulanceActivations: 0, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 0, fatalities: 0 },
    incidentIds: [],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Low-incident cultural performance.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H006,
    venueId: VENUE_IDS.V007,  // PISA
    eventType: 'sports',
    startDatetime: daysAgo(720),
    endDatetime: daysAgo(720) + 6 * 60 * 60 * 1000,
    attendance: 8500,
    registeredCapacity: 12000,
    environment: 'indoor',
    coverage: 'covered',
    seating: 'seated',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-traffic-plan', 'ctrl-medical-team'],
    resourcesPlanned: { police: 18, security: 25, medicalTeams: 2, ambulances: 1, toilets: 35, wasteBins: 90, fireOfficers: 4 },
    resourcesActuallyUsed: { police: 18, security: 25, medicalTeams: 2, ambulances: 1, toilets: 32, wasteBins: 80, fireOfficers: 4 },
    outcomes: { patientPresentations: 11, hospitalTransfers: 1, ambulanceActivations: 1, crowdIncidents: 1, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 2, fatalities: 0 },
    incidentIds: ['hist-inc-008'],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Standard sports event.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H007,
    venueId: VENUE_IDS.V003,  // KLCC
    eventType: 'fair',
    startDatetime: daysAgo(190),
    endDatetime: daysAgo(190) + 8 * 60 * 60 * 1000,
    attendance: 3200,
    registeredCapacity: 20000,
    environment: 'indoor',
    coverage: 'covered',
    seating: 'mixed',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-fire-cert', 'ctrl-medical-team'],
    resourcesPlanned: { police: 8, security: 14, medicalTeams: 1, ambulances: 1, toilets: 14, wasteBins: 35, fireOfficers: 2 },
    resourcesActuallyUsed: { police: 8, security: 13, medicalTeams: 1, ambulances: 1, toilets: 13, wasteBins: 32, fireOfficers: 2 },
    outcomes: { patientPresentations: 5, hospitalTransfers: 0, ambulanceActivations: 0, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 1, fatalities: 0 },
    incidentIds: [],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Indoor fair with low incident rate.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H008,
    venueId: VENUE_IDS.V005,
    eventType: 'religious',
    startDatetime: daysAgo(450),
    endDatetime: daysAgo(450) + 4 * 60 * 60 * 1000,
    attendance: 12000,
    registeredCapacity: 80000,
    environment: 'outdoor',
    coverage: 'uncovered',
    seating: 'mixed',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-medical-team'],
    resourcesPlanned: { police: 25, security: 38, medicalTeams: 3, ambulances: 2, toilets: 50, wasteBins: 120, fireOfficers: 6 },
    resourcesActuallyUsed: { police: 28, security: 42, medicalTeams: 3, ambulances: 2, toilets: 48, wasteBins: 115, fireOfficers: 6 },
    outcomes: { patientPresentations: 18, hospitalTransfers: 2, ambulanceActivations: 2, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 3, fatalities: 0 },
    incidentIds: ['hist-inc-009', 'hist-inc-010'],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Large religious gathering; medical team expanded.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H009,
    venueId: VENUE_IDS.V001,  // Dataran Merdeka
    eventType: 'exhibition',
    startDatetime: daysAgo(800),
    endDatetime: daysAgo(800) + 5 * 60 * 60 * 1000,
    attendance: 8500,
    registeredCapacity: 50000,
    environment: 'outdoor',
    coverage: 'uncovered',
    seating: 'standing',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-fire-cert'],
    resourcesPlanned: { police: 20, security: 28, medicalTeams: 2, ambulances: 1, toilets: 36, wasteBins: 90, fireOfficers: 4 },
    resourcesActuallyUsed: { police: 20, security: 26, medicalTeams: 2, ambulances: 1, toilets: 34, wasteBins: 85, fireOfficers: 4 },
    outcomes: { patientPresentations: 12, hospitalTransfers: 1, ambulanceActivations: 1, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 1, fatalities: 0 },
    incidentIds: [],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Outdoor exhibition with no significant incidents.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
  {
    historicalEventId: HISTORICAL_EVENT_IDS.H010,
    venueId: VENUE_IDS.V008,  // Esplanade Penang
    eventType: 'concert',
    startDatetime: daysAgo(900),
    endDatetime: daysAgo(900) + 4 * 60 * 60 * 1000,
    attendance: 6800,
    registeredCapacity: 15000,
    environment: 'outdoor',
    coverage: 'uncovered',
    seating: 'standing',
    controlsVerified: ['ctrl-crowd-mgmt', 'ctrl-medical-team'],
    resourcesPlanned: { police: 16, security: 22, medicalTeams: 2, ambulances: 1, toilets: 28, wasteBins: 70, fireOfficers: 3 },
    resourcesActuallyUsed: { police: 16, security: 22, medicalTeams: 2, ambulances: 1, toilets: 26, wasteBins: 65, fireOfficers: 3 },
    outcomes: { patientPresentations: 9, hospitalTransfers: 1, ambulanceActivations: 1, crowdIncidents: 0, securityIncidents: 0, weatherInterruptions: 0, nearMisses: 2, fatalities: 0 },
    incidentIds: [],
    completed: true,
    assessmentEligible: true,
    afterActionFindings: ['Standard outdoor concert.'],
    synthetic: true,
    datasetVersion: '2026-07-24-malaysia-research-v1',
  },
];

// ---------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------
export const findHistoricalEventsForVenue = (venueId: string): HistoricalEventOutcome[] =>
  mockHistoricalEvents.filter((h) => h.venueId === venueId);
